DROP DATABASE IF EXISTS heroku_476df5b133de15b;

CREATE DATABASE heroku_476df5b133de15b;

USE heroku_476df5b133de15b;

CREATE TABLE players (
  id serial PRIMARY KEY,
  personId INT(7) NOT NULL,
  firstName VARCHAR(20) NOT NULL,
  lastName VARCHAR(20) NOT NULL,
  jersey INT(2) NOT NULL,
  pos VARCHAR(3) NOT NULL,
  heightFeet INT(1) NOT NULL,
  heightInches INT(2) NOT NULL,
  weightPounds INT(3) NOT NULL,
  birthDate DATE NOT NULL,
  draftRound INT(1),
  draftPick INT(2),
  draftYear INT(4),
  yearsPro INT(2) NOT NULL,
  tpp NUMERIC(4,1),
  ftp NUMERIC(4,1),
  fgp NUMERIC(4,1),
  ppg NUMERIC(4,1),
  rpg NUMERIC(4,1),
  apg NUMERIC(4,1),
  bpg NUMERIC(4,1),
  mpg NUMERIC(4,1),
  spg NUMERIC(4,1),
  assists INT(4),
  blocks INT(4),
  steals INT(4),
  turnovers INT(4),
  offReb INT(4),
  defReb INT(5),
  totReb INT(5),
  fgm INT(5),
  fga INT(5),
  tpm INT(5),
  tpa INT(5),
  ftm INT(5),
  fta INT(5),
  pFouls INT(4),
  points INT(5),
  gamesPlayed INT(4),
  gamesStarted INT(4),
  plusMinus INT(4),
  min INT(5),
  dd2 INT(4),
  td3 INT(4),
  UNIQUE (personId)
);

CREATE TABLE stats (
  id serial PRIMARY KEY,
  personId INT(7) NOT NULL,
  seasonYear INT(4) NOT NULL,
  topg NUMERIC(4,1) NOT NULL,
  tpp NUMERIC(4,1) NOT NULL,
  ftp NUMERIC(4,1) NOT NULL,
  fgp NUMERIC(4,1) NOT NULL,
  ppg NUMERIC(4,1) NOT NULL,
  rpg NUMERIC(4,1) NOT NULL,
  apg NUMERIC(4,1) NOT NULL,
  bpg NUMERIC(4,1) NOT NULL,
  mpg NUMERIC(4,1) NOT NULL,
  spg NUMERIC(4,1) NOT NULL,
  assists INT(4) NOT NULL,
  blocks INT(4) NOT NULL,
  steals INT(4) NOT NULL,
  turnovers INT(4) NOT NULL,
  offReb INT(4) NOT NULL,
  defReb INT(5) NOT NULL,
  totReb INT(5) NOT NULL,
  fgm INT(5) NOT NULL,
  fga INT(5) NOT NULL,
  tpm INT(5) NOT NULL,
  tpa INT(5) NOT NULL,
  ftm INT(5) NOT NULL,
  fta INT(5) NOT NULL,
  pFouls INT(4) NOT NULL,
  points INT(5) NOT NULL,
  gamesPlayed INT(4) NOT NULL,
  gamesStarted INT(4) NOT NULL,
  plusMinus INT(4) NOT NULL,
  min INT(5) NOT NULL,
  dd2 INT(4) NOT NULL,
  td3 INT(4) NOT NULL
);